#!/bin/bash

PORT="5200"
DOCKER_CONTAINER_NAME="fastapi-app"
DOCKER_IMAGE_NAME="fastapi-cloud-run"

# Escribe acá el comando de build
docker build -t $DOCKER_IMAGE_NAME .

docker run -d --rm -e PORT=$PORT -p $PORT:$PORT --name $DOCKER_CONTAINER_NAME $DOCKER_IMAGE_NAME 
