name: GitHub Classroom Workflow

on: 
  workflow_run:
    workflows: ['Python Integration Tests']
    types:
      - completed

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1

  on-error-tests:
    name: Check error in tests workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
        - run: echo "Tests workflow are failed" && exit 1
